### ISSUE TITLE
When using OVS, sockets are not created in correct dir

### ISSUE THREAD

**Issue by kangasta** [intel/vhost-user-net-plugin#5]
https://github.com/intel/vhost-user-net-plugin/blob/ccb0c43509f9405ddc2b0919e4631994590e7d3f/tests/ovs-config.py#L38

OVS vhost-sock-dir option only seems to support sub directories of `/usr/local/var/run/openvswitch` (http://docs.openvswitch.org/en/latest/topics/dpdk/vhost-user/#vhost-user) so currently socket wont be located in `/var/lib/cni/vhostuser/$CONTAINER_ID/` as expected by the plugin.

**Comment by rkamudhan** [comment]
@kangasta  `/var/lib/cni/vhostuser/$CONTAINER_ID/` is for the saving the rendered netconf for cmdDel and application. 

If you wish for the vhost-user sockets to be created in a sub-directory of /usr/local/var/run/openvswitch, you may specify this directory in the ovsdb like so:
```
$ ovs-vsctl --no-wait \
    set Open_vSwitch . other_config:vhost-sock-dir=subdir
```

Agree that I should update the README for the OVS separately :)

**Comment by kangasta** [comment]
I have edited the ovs_config.py script so that the socket file is moved to `/var/lib/cni/vhostuser/$CONTAINER_ID/` and after this I can use the socket from inside the container similarly that I expect would be the process when using VPP.

From what I have understood, when using VPP as the switch the vpp_config.py creates the sockets to `/var/lib/cni/vhostuser/$CONTAINER_ID/` and these are taken into use from inside the container by mounting the `.../vhostuser/` folder and by using the get-prefix.sh script. Have I understood this correctly?

**Comment by rkamudhan** [comment]
Yes, you are correct on this.

**Comment by rkamudhan** [comment]
@kangasta Can you send me the PR, I will check the changes and merge it?
